package com.example.musicplayer.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data class AppColorTheme(
    val id: String,
    val name: String,
    val emoji: String,
    val lightScheme: ColorScheme,
    val darkScheme: ColorScheme,
    val previewPrimary: Color,
    val previewSecondary: Color,
    val previewTertiary: Color
)

val allColorThemes: List<AppColorTheme> = listOf(

    // ── Classic Blue ──────────────────────────────────────────────────────────
    AppColorTheme(
        id = "classic_blue",
        name = "Classic Blue",
        emoji = "💙",
        lightScheme = lightColorScheme(
            primary = Color(0xFF1A56A0),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD3E4FF),
            onPrimaryContainer = Color(0xFF001C3D),
            secondary = Color(0xFF2E6DA0),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCDE2FF),
            onSecondaryContainer = Color(0xFF001D35),
            tertiary = Color(0xFF3A86B0),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFC8E6FF),
            onTertiaryContainer = Color(0xFF001E2F),
            background = Color(0xFFF5F9FF),
            onBackground = Color(0xFF0D1B2E),
            surface = Color(0xFFF5F9FF),
            onSurface = Color(0xFF0D1B2E),
            surfaceVariant = Color(0xFFD8E4F0),
            onSurfaceVariant = Color(0xFF3A4A5C),
            outline = Color(0xFF5A7088),
            outlineVariant = Color(0xFFC0D4E4),
            inverseSurface = Color(0xFF1C2E40),
            inverseOnSurface = Color(0xFFE8F0FF),
            inversePrimary = Color(0xFF9AC4F8)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF9AC4F8),
            onPrimary = Color(0xFF003060),
            primaryContainer = Color(0xFF004588),
            onPrimaryContainer = Color(0xFFD3E4FF),
            secondary = Color(0xFF90C8F8),
            onSecondary = Color(0xFF003060),
            secondaryContainer = Color(0xFF00487E),
            onSecondaryContainer = Color(0xFFCDE2FF),
            tertiary = Color(0xFF88CFF8),
            onTertiary = Color(0xFF003050),
            tertiaryContainer = Color(0xFF004870),
            onTertiaryContainer = Color(0xFFC8E6FF),
            background = Color(0xFF0A1422),
            onBackground = Color(0xFFD0E4FF),
            surface = Color(0xFF0A1422),
            onSurface = Color(0xFFD0E4FF),
            surfaceVariant = Color(0xFF182840),
            onSurfaceVariant = Color(0xFFA8C4D8),
            outline = Color(0xFF6888A0),
            outlineVariant = Color(0xFF182840),
            inverseSurface = Color(0xFFD0E4FF),
            inverseOnSurface = Color(0xFF0A1422),
            inversePrimary = Color(0xFF1A56A0)
        ),
        previewPrimary = Color(0xFF1A56A0),
        previewSecondary = Color(0xFF2E86AB),
        previewTertiary = Color(0xFF5BBCD6)
    ),

    // ── Spotify Green ─────────────────────────────────────────────────────────
    AppColorTheme(
        id = "spotify_green",
        name = "Spotify Green",
        emoji = "🎵",
        lightScheme = lightColorScheme(
            primary = Color(0xFF1A6B38),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFB2F0C8),
            onPrimaryContainer = Color(0xFF00210E),
            secondary = Color(0xFF2D6B45),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFB0EDCC),
            onSecondaryContainer = Color(0xFF002113),
            tertiary = Color(0xFF3A7A3C),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFBEF0BC),
            onTertiaryContainer = Color(0xFF002200),
            background = Color(0xFFF0FBF3),
            onBackground = Color(0xFF061C0D),
            surface = Color(0xFFF0FBF3),
            onSurface = Color(0xFF061C0D),
            surfaceVariant = Color(0xFFCCE8D4),
            onSurfaceVariant = Color(0xFF364E3C),
            outline = Color(0xFF527858),
            outlineVariant = Color(0xFFB0CEB8),
            inverseSurface = Color(0xFF0E2E18),
            inverseOnSurface = Color(0xFFDEF8E6),
            inversePrimary = Color(0xFF7ADCA0)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF1DB954),
            onPrimary = Color(0xFF003916),
            primaryContainer = Color(0xFF005224),
            onPrimaryContainer = Color(0xFFB2F0C8),
            secondary = Color(0xFF1ED760),
            onSecondary = Color(0xFF003916),
            secondaryContainer = Color(0xFF005224),
            onSecondaryContainer = Color(0xFFB0EDCC),
            tertiary = Color(0xFF5ADA6A),
            onTertiary = Color(0xFF003A12),
            tertiaryContainer = Color(0xFF0A5220),
            onTertiaryContainer = Color(0xFFBEF0BC),
            background = Color(0xFF061009),
            onBackground = Color(0xFFB8E8C6),
            surface = Color(0xFF061009),
            onSurface = Color(0xFFB8E8C6),
            surfaceVariant = Color(0xFF152A1C),
            onSurfaceVariant = Color(0xFF96BEA0),
            outline = Color(0xFF6A9E74),
            outlineVariant = Color(0xFF152A1C),
            inverseSurface = Color(0xFFB8E8C6),
            inverseOnSurface = Color(0xFF061009),
            inversePrimary = Color(0xFF1A6B38)
        ),
        previewPrimary = Color(0xFF1DB954),
        previewSecondary = Color(0xFF158A3E),
        previewTertiary = Color(0xFF4CAF50)
    ),

    // ── Sunset ────────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "sunset_orange",
        name = "Sunset",
        emoji = "🌅",
        lightScheme = lightColorScheme(
            primary = Color(0xFFBF4200),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDBCF),
            onPrimaryContainer = Color(0xFF340E00),
            secondary = Color(0xFFBF5B00),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDCC8),
            onSecondaryContainer = Color(0xFF331600),
            tertiary = Color(0xFFAA7600),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFEAC2),
            onTertiaryContainer = Color(0xFF341C00),
            background = Color(0xFFFFF8F5),
            onBackground = Color(0xFF201200),
            surface = Color(0xFFFFF8F5),
            onSurface = Color(0xFF201200),
            surfaceVariant = Color(0xFFF4DFCF),
            onSurfaceVariant = Color(0xFF533A28),
            outline = Color(0xFF855040),
            outlineVariant = Color(0xFFD9BFAF),
            inverseSurface = Color(0xFF38200A),
            inverseOnSurface = Color(0xFFFFECE0),
            inversePrimary = Color(0xFFFFB598)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFF8C42),
            onPrimary = Color(0xFF4A1800),
            primaryContainer = Color(0xFF6A2800),
            onPrimaryContainer = Color(0xFFFFDBCF),
            secondary = Color(0xFFFFAB60),
            onSecondary = Color(0xFF4A2000),
            secondaryContainer = Color(0xFF6A3200),
            onSecondaryContainer = Color(0xFFFFDCC8),
            tertiary = Color(0xFFFFCC70),
            onTertiary = Color(0xFF442500),
            tertiaryContainer = Color(0xFF5F3600),
            onTertiaryContainer = Color(0xFFFFEAC2),
            background = Color(0xFF120D04),
            onBackground = Color(0xFFF5DCCF),
            surface = Color(0xFF120D04),
            onSurface = Color(0xFFF5DCCF),
            surfaceVariant = Color(0xFF3A2518),
            onSurfaceVariant = Color(0xFFD4B9AC),
            outline = Color(0xFF9E7562),
            outlineVariant = Color(0xFF3A2518),
            inverseSurface = Color(0xFFF5DCCF),
            inverseOnSurface = Color(0xFF120D04),
            inversePrimary = Color(0xFFBF4200)
        ),
        previewPrimary = Color(0xFFE65100),
        previewSecondary = Color(0xFFFF6D00),
        previewTertiary = Color(0xFFFFAB40)
    ),

    // ── Ocean ─────────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "ocean_teal",
        name = "Ocean",
        emoji = "🌊",
        lightScheme = lightColorScheme(
            primary = Color(0xFF006A5B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFBCEDE4),
            onPrimaryContainer = Color(0xFF00201B),
            secondary = Color(0xFF00847A),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFB8EBE4),
            onSecondaryContainer = Color(0xFF001B17),
            tertiary = Color(0xFF228080),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFC0EBE8),
            onTertiaryContainer = Color(0xFF002020),
            background = Color(0xFFF0FAFA),
            onBackground = Color(0xFF051F1E),
            surface = Color(0xFFF0FAFA),
            onSurface = Color(0xFF051F1E),
            surfaceVariant = Color(0xFFCCE5E2),
            onSurfaceVariant = Color(0xFF354A49),
            outline = Color(0xFF527878),
            outlineVariant = Color(0xFFAEC8C8),
            inverseSurface = Color(0xFF0E2C2C),
            inverseOnSurface = Color(0xFFDEF8F6),
            inversePrimary = Color(0xFF80D8CC)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF4DB6AC),
            onPrimary = Color(0xFF003732),
            primaryContainer = Color(0xFF005048),
            onPrimaryContainer = Color(0xFFBCEDE4),
            secondary = Color(0xFF80CBC4),
            onSecondary = Color(0xFF003630),
            secondaryContainer = Color(0xFF004E46),
            onSecondaryContainer = Color(0xFFB8EBE4),
            tertiary = Color(0xFF80C8C8),
            onTertiary = Color(0xFF003636),
            tertiaryContainer = Color(0xFF004E50),
            onTertiaryContainer = Color(0xFFC0EBE8),
            background = Color(0xFF060F0F),
            onBackground = Color(0xFFB4D4D2),
            surface = Color(0xFF060F0F),
            onSurface = Color(0xFFB4D4D2),
            surfaceVariant = Color(0xFF182E2C),
            onSurfaceVariant = Color(0xFF9ABFBC),
            outline = Color(0xFF689F9C),
            outlineVariant = Color(0xFF182E2C),
            inverseSurface = Color(0xFFB4D4D2),
            inverseOnSurface = Color(0xFF060F0F),
            inversePrimary = Color(0xFF006A5B)
        ),
        previewPrimary = Color(0xFF00695C),
        previewSecondary = Color(0xFF00897B),
        previewTertiary = Color(0xFF26A69A)
    ),

    // ── Purple Haze ───────────────────────────────────────────────────────────
    AppColorTheme(
        id = "purple_haze",
        name = "Purple Haze",
        emoji = "💜",
        lightScheme = lightColorScheme(
            primary = Color(0xFF6A1B9A),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFEDD5FF),
            onPrimaryContainer = Color(0xFF22005D),
            secondary = Color(0xFF7A3B8C),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF2DAFF),
            onSecondaryContainer = Color(0xFF2D0050),
            tertiary = Color(0xFF9048A0),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFF9DEFF),
            onTertiaryContainer = Color(0xFF360040),
            background = Color(0xFFFEF7FF),
            onBackground = Color(0xFF1D1020),
            surface = Color(0xFFFEF7FF),
            onSurface = Color(0xFF1D1020),
            surfaceVariant = Color(0xFFE8DEF8),
            onSurfaceVariant = Color(0xFF49454F),
            outline = Color(0xFF79747E),
            outlineVariant = Color(0xFFCAC4D0),
            inverseSurface = Color(0xFF322036),
            inverseOnSurface = Color(0xFFF6EEFF),
            inversePrimary = Color(0xFFD4AAFF)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFD4AAFF),
            onPrimary = Color(0xFF3B0071),
            primaryContainer = Color(0xFF52009B),
            onPrimaryContainer = Color(0xFFEDD5FF),
            secondary = Color(0xFFDDAAFF),
            onSecondary = Color(0xFF49006D),
            secondaryContainer = Color(0xFF610090),
            onSecondaryContainer = Color(0xFFF2DAFF),
            tertiary = Color(0xFFEFAAFF),
            onTertiary = Color(0xFF590065),
            tertiaryContainer = Color(0xFF7A0090),
            onTertiaryContainer = Color(0xFFF9DEFF),
            background = Color(0xFF100816),
            onBackground = Color(0xFFE8D8EF),
            surface = Color(0xFF100816),
            onSurface = Color(0xFFE8D8EF),
            surfaceVariant = Color(0xFF2B1A34),
            onSurfaceVariant = Color(0xFFCAC4D0),
            outline = Color(0xFF938F99),
            outlineVariant = Color(0xFF49454F),
            inverseSurface = Color(0xFFE8D8EF),
            inverseOnSurface = Color(0xFF100816),
            inversePrimary = Color(0xFF6A1B9A)
        ),
        previewPrimary = Color(0xFF6A1B9A),
        previewSecondary = Color(0xFF8E24AA),
        previewTertiary = Color(0xFFAB47BC)
    ),

    // ── Rose ──────────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "rose_pink",
        name = "Rose",
        emoji = "🌹",
        lightScheme = lightColorScheme(
            primary = Color(0xFFA8004A),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFD9E3),
            onPrimaryContainer = Color(0xFF3C0017),
            secondary = Color(0xFFB8205A),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD8E0),
            onSecondaryContainer = Color(0xFF3D001C),
            tertiary = Color(0xFFB44090),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD8EE),
            onTertiaryContainer = Color(0xFF3D0030),
            background = Color(0xFFFFF5F8),
            onBackground = Color(0xFF200015),
            surface = Color(0xFFFFF5F8),
            onSurface = Color(0xFF200015),
            surfaceVariant = Color(0xFFF4DADF),
            onSurfaceVariant = Color(0xFF533A40),
            outline = Color(0xFF855060),
            outlineVariant = Color(0xFFD9BFBF),
            inverseSurface = Color(0xFF380020),
            inverseOnSurface = Color(0xFFFFECF0),
            inversePrimary = Color(0xFFFFB0C8)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFFB0C8),
            onPrimary = Color(0xFF650028),
            primaryContainer = Color(0xFF8E003C),
            onPrimaryContainer = Color(0xFFFFD9E3),
            secondary = Color(0xFFFFB0C0),
            onSecondary = Color(0xFF650028),
            secondaryContainer = Color(0xFF8E0038),
            onSecondaryContainer = Color(0xFFFFD8E0),
            tertiary = Color(0xFFFFAAD4),
            onTertiary = Color(0xFF65004A),
            tertiaryContainer = Color(0xFF8E0066),
            onTertiaryContainer = Color(0xFFFFD8EE),
            background = Color(0xFF14080D),
            onBackground = Color(0xFFF0D8DF),
            surface = Color(0xFF14080D),
            onSurface = Color(0xFFF0D8DF),
            surfaceVariant = Color(0xFF38181E),
            onSurfaceVariant = Color(0xFFD4B8BC),
            outline = Color(0xFFA07878),
            outlineVariant = Color(0xFF38181E),
            inverseSurface = Color(0xFFF0D8DF),
            inverseOnSurface = Color(0xFF14080D),
            inversePrimary = Color(0xFFA8004A)
        ),
        previewPrimary = Color(0xFFC2185B),
        previewSecondary = Color(0xFFE91E63),
        previewTertiary = Color(0xFFF48FB1)
    ),

    // ── Midnight ──────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "midnight",
        name = "Midnight",
        emoji = "🌙",
        lightScheme = lightColorScheme(
            primary = Color(0xFF37474F),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFCFDDE3),
            onPrimaryContainer = Color(0xFF0C1619),
            secondary = Color(0xFF546E7A),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCEDEE4),
            onSecondaryContainer = Color(0xFF131C1F),
            tertiary = Color(0xFF607D8B),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFCFDEE6),
            onTertiaryContainer = Color(0xFF131D22),
            background = Color(0xFFF4F7F9),
            onBackground = Color(0xFF111518),
            surface = Color(0xFFF4F7F9),
            onSurface = Color(0xFF111518),
            surfaceVariant = Color(0xFFD8E2E6),
            onSurfaceVariant = Color(0xFF384448),
            outline = Color(0xFF5A6C72),
            outlineVariant = Color(0xFFB8C8CE),
            inverseSurface = Color(0xFF1E2A30),
            inverseOnSurface = Color(0xFFE8F0F4),
            inversePrimary = Color(0xFFA0C0CA)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFBB86FC),
            onPrimary = Color(0xFF1A0040),
            primaryContainer = Color(0xFF2C0060),
            onPrimaryContainer = Color(0xFFE8CCFF),
            secondary = Color(0xFF03DAC6),
            onSecondary = Color(0xFF003630),
            secondaryContainer = Color(0xFF005048),
            onSecondaryContainer = Color(0xFFB8EDE8),
            tertiary = Color(0xFFCF6679),
            onTertiary = Color(0xFF3A0015),
            tertiaryContainer = Color(0xFF560028),
            onTertiaryContainer = Color(0xFFFFD8E0),
            background = Color(0xFF000000),
            onBackground = Color(0xFFE0E0E0),
            surface = Color(0xFF1F1F1F),
            onSurface = Color(0xFFE0E0E0),
            surfaceVariant = Color(0xFF2C2C2C),
            onSurfaceVariant = Color(0xFFAAAAAA),
            outline = Color(0xFF777777),
            outlineVariant = Color(0xFF2C2C2C),
            inverseSurface = Color(0xFFE0E0E0),
            inverseOnSurface = Color(0xFF1F1F1F),
            inversePrimary = Color(0xFF37474F)
        ),
        previewPrimary = Color(0xFF1A1A2E),
        previewSecondary = Color(0xFFBB86FC),
        previewTertiary = Color(0xFF03DAC6)
    ),

    // ── Forest ────────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "forest",
        name = "Forest",
        emoji = "🌲",
        lightScheme = lightColorScheme(
            primary = Color(0xFF2E7D32),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFB8F0B8),
            onPrimaryContainer = Color(0xFF002200),
            secondary = Color(0xFF388E3C),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFB8F0BC),
            onSecondaryContainer = Color(0xFF002208),
            tertiary = Color(0xFF558B58),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFCC8EEC8),
            onTertiaryContainer = Color(0xFF082408),
            background = Color(0xFFF2F8F2),
            onBackground = Color(0xFF081808),
            surface = Color(0xFFF2F8F2),
            onSurface = Color(0xFF081808),
            surfaceVariant = Color(0xFFCEE5CE),
            onSurfaceVariant = Color(0xFF344834),
            outline = Color(0xFF507050),
            outlineVariant = Color(0xFFB0CCB0),
            inverseSurface = Color(0xFF102810),
            inverseOnSurface = Color(0xFFE2F2E2),
            inversePrimary = Color(0xFF88CC88)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF81C784),
            onPrimary = Color(0xFF003A08),
            primaryContainer = Color(0xFF005218),
            onPrimaryContainer = Color(0xFFB8F0B8),
            secondary = Color(0xFFA5D6A7),
            onSecondary = Color(0xFF003A0A),
            secondaryContainer = Color(0xFF00521A),
            onSecondaryContainer = Color(0xFFB8F0BC),
            tertiary = Color(0xFFC8E6C9),
            onTertiary = Color(0xFF003A08),
            tertiaryContainer = Color(0xFF1A4A1C),
            onTertiaryContainer = Color(0xFFC8EEC8),
            background = Color(0xFF071007),
            onBackground = Color(0xFFB8DEB8),
            surface = Color(0xFF071007),
            onSurface = Color(0xFFB8DEB8),
            surfaceVariant = Color(0xFF142814),
            onSurfaceVariant = Color(0xFF98BE98),
            outline = Color(0xFF669866),
            outlineVariant = Color(0xFF142814),
            inverseSurface = Color(0xFFB8DEB8),
            inverseOnSurface = Color(0xFF071007),
            inversePrimary = Color(0xFF2E7D32)
        ),
        previewPrimary = Color(0xFF2E7D32),
        previewSecondary = Color(0xFF388E3C),
        previewTertiary = Color(0xFF66BB6A)
    ),

    // ── Golden ────────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "golden",
        name = "Golden",
        emoji = "✨",
        lightScheme = lightColorScheme(
            primary = Color(0xFF8A6000),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFEAA0),
            onPrimaryContainer = Color(0xFF261A00),
            secondary = Color(0xFF9A7000),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFE9A0),
            onSecondaryContainer = Color(0xFF2A1C00),
            tertiary = Color(0xFF7A6500),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFECC0),
            onTertiaryContainer = Color(0xFF221B00),
            background = Color(0xFFFFFDF0),
            onBackground = Color(0xFF201A00),
            surface = Color(0xFFFFFDF0),
            onSurface = Color(0xFF201A00),
            surfaceVariant = Color(0xFFF0E8CC),
            onSurfaceVariant = Color(0xFF4E4424),
            outline = Color(0xFF786840),
            outlineVariant = Color(0xFFD8CC9A),
            inverseSurface = Color(0xFF342C00),
            inverseOnSurface = Color(0xFFFFF3C0),
            inversePrimary = Color(0xFFFFCC40)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFFCC40),
            onPrimary = Color(0xFF3A2800),
            primaryContainer = Color(0xFF543A00),
            onPrimaryContainer = Color(0xFFFFEAA0),
            secondary = Color(0xFFFFD740),
            onSecondary = Color(0xFF3A2C00),
            secondaryContainer = Color(0xFF544000),
            onSecondaryContainer = Color(0xFFFFE9A0),
            tertiary = Color(0xFFFFCC70),
            onTertiary = Color(0xFF3A2C00),
            tertiaryContainer = Color(0xFF544000),
            onTertiaryContainer = Color(0xFFFFECC0),
            background = Color(0xFF110F00),
            onBackground = Color(0xFFF0D840),
            surface = Color(0xFF110F00),
            onSurface = Color(0xFFEEDDAA),
            surfaceVariant = Color(0xFF2C2400),
            onSurfaceVariant = Color(0xFFCCBE80),
            outline = Color(0xFF9A8A50),
            outlineVariant = Color(0xFF2C2400),
            inverseSurface = Color(0xFFEEDDAA),
            inverseOnSurface = Color(0xFF110F00),
            inversePrimary = Color(0xFF8A6000)
        ),
        previewPrimary = Color(0xFFF9A825),
        previewSecondary = Color(0xFFFBC02D),
        previewTertiary = Color(0xFFFFD54F)
    ),

    // ── Cherry ────────────────────────────────────────────────────────────────
    AppColorTheme(
        id = "cherry",
        name = "Cherry",
        emoji = "🍒",
        lightScheme = lightColorScheme(
            primary = Color(0xFFB00020),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDADB),
            onPrimaryContainer = Color(0xFF3C0008),
            secondary = Color(0xFFBF2030),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD8D9),
            onSecondaryContainer = Color(0xFF3D000D),
            tertiary = Color(0xFFC04050),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD8DC),
            onTertiaryContainer = Color(0xFF3D0010),
            background = Color(0xFFFFF5F5),
            onBackground = Color(0xFF200006),
            surface = Color(0xFFFFF5F5),
            onSurface = Color(0xFF200006),
            surfaceVariant = Color(0xFFF4DADB),
            onSurfaceVariant = Color(0xFF533A3B),
            outline = Color(0xFF855055),
            outlineVariant = Color(0xFFD9BFBF),
            inverseSurface = Color(0xFF380010),
            inverseOnSurface = Color(0xFFFFECEC),
            inversePrimary = Color(0xFFFFB3B6)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFFB3B6),
            onPrimary = Color(0xFF680018),
            primaryContainer = Color(0xFF920028),
            onPrimaryContainer = Color(0xFFFFDADB),
            secondary = Color(0xFFFFB0B8),
            onSecondary = Color(0xFF680018),
            secondaryContainer = Color(0xFF920022),
            onSecondaryContainer = Color(0xFFFFD8D9),
            tertiary = Color(0xFFFFAAB5),
            onTertiary = Color(0xFF68001C),
            tertiaryContainer = Color(0xFF920030),
            onTertiaryContainer = Color(0xFFFFD8DC),
            background = Color(0xFF150404),
            onBackground = Color(0xFFF0D8D9),
            surface = Color(0xFF150404),
            onSurface = Color(0xFFF0D8D9),
            surfaceVariant = Color(0xFF381818),
            onSurfaceVariant = Color(0xFFD4B8B9),
            outline = Color(0xFFA07878),
            outlineVariant = Color(0xFF381818),
            inverseSurface = Color(0xFFF0D8D9),
            inverseOnSurface = Color(0xFF150404),
            inversePrimary = Color(0xFFB00020)
        ),
        previewPrimary = Color(0xFFB71C1C),
        previewSecondary = Color(0xFFD32F2F),
        previewTertiary = Color(0xFFEF5350)
    )
)

fun colorThemeById(id: String): AppColorTheme =
    allColorThemes.find { it.id == id } ?: allColorThemes.first()
